#!/bin/sh

CONTEXT_DIR=/mnt/.rw/context
AMICONFIG_CONTEXT_DIR=/var/lib/amiconfig

setupContext() {
  VERSION="2007-12-15"
  if [ -e $CONTEXT_DIR/context.sh ]; then
    # OpenNebula
    . $CONTEXT_DIR/context.sh
    mkdir -p $AMICONFIG_CONTEXT_DIR/${VERSION}
    if [ "x$EC2_USER_DATA" != "x" ] ; then
      echo $EC2_USER_DATA | base64 -di > $AMICONFIG_CONTEXT_DIR/${VERSION}/user-data 2>/dev/null
    fi
    ssh_keyfile=$CONTEXT_DIR/$ROOT_PUBKEY 
    if [ "x$PUBLIC_KEY" != "x" ]; then
      ssh_keyfile=/tmp/authorized_keys.$$
      echo "$PUBLIC_KEY" > $ssh_keyfile
    fi
    if [ -f $ssh_keyfile ] ; then
      mkdir -p $AMICONFIG_CONTEXT_DIR/${VERSION}/meta-data/public-keys/0
      mv -f $ssh_keyfile $AMICONFIG_CONTEXT_DIR/${VERSION}/meta-data/public-keys/0/openssh-key
    fi
    if [ -e /etc/sysconfig/amiconfig ]; then
      amiconf=`cat /etc/sysconfig/amiconfig | grep -v AMICONFIG_CONTEXT_URL`
      echo $amiconf > /etc/sysconfig/amiconfig
    fi
    echo "export AMICONFIG_CONTEXT_URL=file:$AMICONFIG_CONTEXT_DIR/${VERSION}" >> /etc/sysconfig/amiconfig
    . /etc/sysconfig/amiconfig
    chmod -R 700 $AMICONFIG_CONTEXT_DIR
    return 0
    
  elif [ -e "$CONTEXT_DIR/user-data" -a -e "$CONTEXT_DIR/meta-data.json" ]; then
    # OpenStack ConfigDrive
    rm -rf "${AMICONFIG_CONTEXT_DIR}/${VERSION}"
    mkdir -p "${AMICONFIG_CONTEXT_DIR}/${VERSION}"
    cp $CONTEXT_DIR/user-data "${AMICONFIG_CONTEXT_DIR}/${VERSION}/user-data"

    # JSON to directory structure (easier to parse in Python)
    Py='/tmp/context-json-to-dir.py'
    cat > "$Py" <<_EoF_
import json, os
def recursive_explore(p, d):
    for k,v in d.iteritems():
        if isinstance(v, dict):
            recursive_explore(p+k+'/', v)
        elif v is not None:
            if not os.path.isdir(p):
                os.makedirs(p)
            g = open(p+k, 'w')
            g.write( str(v) )
            g.close()
            print "%s%s = %s" % (p, k, v)
f = open("$CONTEXT_DIR/meta-data.json")
d = json.loads(f.read())
recursive_explore('${AMICONFIG_CONTEXT_DIR}/${VERSION}/meta-data/', d)
_EoF_
    python "$Py" > /dev/null 2> /dev/null
    rm -f "$Py"

    # Tell amiconfig.sh where is all the stuff
    echo "export AMICONFIG_CONTEXT_URL=file:${AMICONFIG_CONTEXT_DIR}/${VERSION}" > /etc/sysconfig/amiconfig

    # Enforce strict permissions
    chmod u=rwX,g=,o= -R $CONTEXT_DIR
    return 0

  elif [ -e "$CONTEXT_DIR"/user-data ]; then
    # Unknown source, e.g. EC2, Azure
    rm -rf "${AMICONFIG_CONTEXT_DIR}/${VERSION}"
    mkdir -p "${AMICONFIG_CONTEXT_DIR}/${VERSION}"
    cp $CONTEXT_DIR/user-data "${AMICONFIG_CONTEXT_DIR}/${VERSION}/user-data"
    echo "export AMICONFIG_CONTEXT_URL=file:${AMICONFIG_CONTEXT_DIR}/${VERSION}" > /etc/sysconfig/amiconfig
    return 0 
  fi
  return 1
}

setupContext
if [ $? -eq 0 ]; then
  /usr/sbin/amiconfig.sh user
fi

