#!/bin/sh

. /etc/cernvm/functions

[ -x /etc/cernvm/config ] && /etc/cernvm/config
read_conf default tools site custom
cernvm_init_dir="/etc/cernvm/cernvm.d"
  [ -d $cernvm_init_dir ] && cernvm_scripts=`ls $cernvm_init_dir/*.sh`

RETVAL=0
for f in ${cernvm_scripts}
do
  ( . $f; 
    [ -f /etc/cernvm/custom/init.sh ] && . /etc/cernvm/custom/init.sh
    [ x`type -t cernvm_start` = x"function" ] && cernvm_start || exit 1 
  )
  RETVAL=$[$RETVAL+$?]
done

exit $RETVAL

